### PR TITLE
bug: make json decode save

### LINKED ISSUE #15: "Unexpected end of input" error in JS projects
Hi,

Recently I started getting some strange errors in JS projects. Seems like it's failing to read package-lock.json or something like that.

**Minimal init.vim**
```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
set packpath=/tmp/nvim/site
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
Plug 'lukas-reineke/cmp-rg'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
    { name = "rg" },
  },
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
EOF
```

**Steps to reproduce**:

1. Clone some js repository, for example `coc.nvim`: `git clone https://github.com/neoclide/coc.nvim`
2. cd into the folder, and start neovim with the mininit above `nvim -u mininit.vim src/events.ts` with some file opened
3. Try typing something to trigger autocomplete
4. Do `:messages` to see the errors

Here's small chunk what I get:
```
stack traceback:                                                                                                                                                                                                                      
^I[C]: in function 'json_decode'
^I/tmp/plugged/vim-plug/cmp-rg/lua/cmp-rg/init.lua:29: in function </tmp/plugged/vim-plug/cmp-rg/lua/cmp-rg/init.lua:25> function: builtin#18 Vim:E474: Unexpected end of input: {"type":"context","data":{"path":{"text":"./src/__tests__/tree/
basicProvider.test.ts"},"lines":{"text":"        expect(node).toBe(b)\n"},"line_number":311,"absolute_offset":8834,"submatches":
stack traceback:
^I[C]: in function 'json_decode'
^I/tmp/plugged/vim-plug/cmp-rg/lua/cmp-rg/init.lua:29: in function </tmp/plugged/vim-plug/cmp-rg/lua/cmp-rg/init.lua:25> function: builtin#18 Vim:E474: Trailing characters: }}
stack traceback:
```

### PR DESCRIPTION
**Pull request by lukas-reineke**
fix #15

### CODE REVIEW

**Comment by pedro757** [comment]
The error change, now it does not crash neovim 

^I...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:34: in function <...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:25>
^I...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:34: in function <...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:25> function: builtin#18 ...e/nvim/site/pack/packer/start/cmp-rg/l
^I...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:34: in function <...e/nvim/site/pack/packer/start/cmp-rg/lua/cmp-rg/init.lua:25>

**Comment by lukas-reineke** [comment]
This is not the full error message, it is missing the actual error.

**Review by kristijanhusak — APPROVED** [review]

**Comment by lukas-reineke** [comment]
@pedro757 if you still get this error, please open a new issue with the full error message

**Comment by pedro757** [comment]
> This is not the full error message, it is missing the actual error.

Where can I get the logs?

**Comment by lukas-reineke** [comment]
You can see the whole output with `:message`

**Pull request merged**
