### PR TITLE
Fix quote problem in Windows

### PR DESCRIPTION
**Pull request by UnderCooled**
Windows cmd.exe uses `"` as quote mark.

### CODE REVIEW

**Review by lukas-reineke — CHANGES_REQUESTED** [review]
thank you
code looks good, but please format it with [stylua](https://github.com/johnnymorganz/stylua)

**Comment by lukas-reineke** [comment]
I had some time now to test, and it actually doesn't matter what quote you use on Mac and Linux.
So can you change it to just use `"` always?

**Comment by UnderCooled** [comment]
I believe in bash `'` `"` are different, something about variable expansion.

**Comment by lukas-reineke** [comment]
> I believe in bash `'` `"` are different, something about variable expansion.

Right.. It shouldn't matter in most cases, but we should keep it :+1:

**Review by lukas-reineke — APPROVED** [review]

**Pull request merged**
